services:

  db:
    image: mysql
    ports: 
      - 3306:3306
    volumes:
      - ./datadir:/var/lib/mysql
    env_file: ./src/.env
    networks:
      - app_network

  app:
    build: .
    ports:
      - 8080:80
    volumes: 
      - ./src:/var/www/html
    env_file: ./src/.env
    networks: 
      - app_network

networks:

  app_network:
    driver: bridge